const NFTS = [
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 1,
    image: "/assets/images/nft-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
];

export default NFTS;
