const advS = [
  {
    id: 1,
    image: "/assets/images/adv-1.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 2,
    image: "/assets/images/adv-2.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 3,
    image: "/assets/images/adv-3.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 4,
    image: "/assets/images/adv-4.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 5,
    image: "/assets/images/adv-5.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 6,
    image: "/assets/images/adv-6.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 7,
    image: "/assets/images/adv-7.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 8,
    image: "/assets/images/adv-8.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 9,
    image: "/assets/images/adv-9.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 10,
    image: "/assets/images/adv-10.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 11,
    image: "/assets/images/adv-11.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 12,
    image: "/assets/images/adv-12.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 13,
    image: "/assets/images/adv-13.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 14,
    image: "/assets/images/adv-14.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 15,
    image: "/assets/images/adv-15.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 16,
    image: "/assets/images/adv-16.png",
    title: "Desert King",
    price: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
];

export default advS;
